add-highlighter global number_lines -relative
colorscheme solarized-light
set global tabstop 4

set global grepcmd 'rg --column'

# LSP
%sh{kak-lsp --kakoune -s $kak_session}
lsp-start
lsp-auto-hover-enable

# Copy/Paste
hook global NormalKey y|d|c %{ nop %sh{
    printf %s "$kak_reg_dquote" | xsel --input --clipboard
}}

# User mode key bindings
map global user f :fzf-file<ret> -docstring 'fzf-file'
map global user b :fzf-buffer<ret> -docstring 'fzf-buffer'
