source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug https://github.com/robertmeta/plug.kak noload

plug https://github.com/andreyorst/powerline.kak config %{
    hook global ModuleLoaded powerline %{
        powerline-theme solarized-light
    }
    powerline-start
}

set global tabstop 8

set global grepcmd 'rg --column'

# Highlighting
add-highlighter global/ number-lines
add-highlighter global/ show-matching
add-highlighter global/ column '%opt{autowrap_column}' MenuBackground
add-highlighter global/ regex \h+$ 0:Error  # Trailing whitespace
add-highlighter global/ show-whitespaces

## Highlight search
set-face global search +bi
add-highlighter global/search dynregex '%reg{/}' 0:search

hook global WinSetOption 'filetype=(git-.*|mail)' %{
  set-option buffer autowrap_column 75
}

# LSP
evaluate-commands %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable
lsp-auto-hover-enable

# Copy/Paste
hook global NormalKey y|d|c %{ nop %sh{
    printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}

# Indent/deindent with spaces when hitting <tab>
hook global InsertChar \t %{ try %{
  execute-keys -draft "h<a-h><a-k>\A\h+\z<ret><a-;>;%opt{indentwidth}@"
}}
map global insert <s-tab> '<a-;><lt>'

colorscheme gruvbox-light
# Hack to avoid using termcolors in the *grep* buffer:
hook -group grep-highlight global WinSetOption filetype=grep %{
    add-highlighter window/grep/ regex "^((?:\w:)?[^:\n]+):(\d+):(\d+)?" 1:function 2:value 3:value
}
