colorscheme solarized-light
set global tabstop 4

set global grepcmd 'rg --column'

# Highlighting
source "%val{config}/gruvbox-light.kak"

add-highlighter global/ number-lines
add-highlighter global/ show-matching
add-highlighter global/ column '%opt{autowrap_column}' StatusLine

## Highlight search
set-face global search +bi
add-highlighter global/search dynregex '%reg{/}' 0:search

# LSP
evaluate-commands %sh{kak-lsp --kakoune -s $kak_session}
lsp-start
lsp-auto-hover-enable

# Copy/Paste
hook global NormalKey y|d|c %{ nop %sh{
    printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}

# Indent/deindent with spaces when hitting <tab>
hook global InsertChar \t %{ try %{
  execute-keys -draft "h<a-h><a-k>\A\h+\z<ret><a-;>;%opt{indentwidth}@"
}}
map global insert <s-tab> '<a-;><lt>'

# User mode key bindings
map global user f :fzf-file<ret> -docstring 'fzf-file'
map global user b :fzf-buffer<ret> -docstring 'fzf-buffer'
